name: Rust

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Sensor tests
        run: cargo test --manifest-path=sensors/Cargo.toml
      - name: Fusion tests
        run: cargo test --manifest-path=sensor_fusion/Cargo.toml
      - name: Robot tests
        run: cargo test --manifest-path=robot/Cargo.toml